### ISSUE TITLE
Reading files from S3 fails with compressed folder of files

### ISSUE THREAD

**Issue by mdavis-xyz** [awslabs/aws-data-wrangler#1031]
**Describe the bug**

I want to do `wr.s3.read_csv('s3://mybucket/prefix/')` to read in a bunch of files from S3, where some are `.csv` and some are `.csv.gz`.

#175 resolved an issue for this when the argument to `read_csv` is a single file, or a folder where all files have the same compression. It seems to not be working for a folder of files with some `.csv` and some `.gz`.

@igorborgest  @jar-no1

Note that AWS Glue can handle this fine. My use case is that I want to compress most of my files. But some are tiny so it's not worth the overhead of compressing those.

**Environment**

```
$ pip3 list
Package               Version
--------------------- ---------
arrow                 1.1.0
asn1crypto            1.4.0
attrs                 20.3.0
aws-lambda-builders   1.3.0
aws-sam-cli           1.23.0
aws-sam-translator    1.35.0
awsebcli              3.19.4
awswrangler           2.12.1
bcrypt                3.2.0
beautifulsoup4        4.10.0
binaryornot           0.4.4
blessed               1.18.0
boto3                 1.17.66
botocore              1.20.66
cached-property       1.5.2
cement                2.8.2
certifi               2020.12.5
cffi                  1.14.5
chardet               3.0.4
chevron               0.14.0
click                 7.1.2
colorama              0.4.3
cookiecutter          1.7.2
cryptography          3.3.1
dateparser            0.7.6
decorator             5.1.0
docker                4.2.2
docker-compose        1.25.5
dockerpty             0.4.1
docopt                0.6.2
et-xmlfile            1.1.0
Flask                 1.1.2
future                0.16.0
git-remote-codecommit 1.15.1
idna                  2.10
importlib-metadata    4.0.1
itsdangerous          1.1.0
Jinja2                2.11.3
jinja2-time           0.2.0
jmespath              0.10.0
jsonpath-ng           1.5.3
jsonschema            3.2.0
lxml                  4.6.4
MarkupSafe            1.1.1
numpy                 1.21.4
openpyxl              3.0.9
opensearch-py         1.0.0
packaging             21.3
pandas                1.3.4
paramiko              2.7.2
pathspec              0.5.9
pathtools             0.1.2
pg8000                1.21.3
pip                   20.2.2
ply                   3.11
poyo                  0.5.0
progressbar2          3.55.0
pyarrow               5.0.0
pycparser             2.20
PyMySQL               1.0.2
PyNaCl                1.4.0
pyparsing             3.0.6
pyrsistent            0.17.3
python-dateutil       2.8.1
python-slugify        5.0.0
python-utils          2.5.6
pytz                  2021.1
PyYAML                5.3.1
redshift-connector    2.0.900
regex                 2021.4.4
requests              2.23.0
requests-aws4auth     1.1.1
s3transfer            0.4.2
scramp                1.4.1
semantic-version      2.8.5
serverlessrepo        0.1.10
setuptools            49.1.3
six                   1.14.0
soupsieve             2.3.1
termcolor             1.1.0
text-unidecode        1.3
texttable             1.6.3
tomlkit               0.7.0
typing-extensions     3.10.0.0
tzlocal               2.1
urllib3               1.25.11
watchdog              0.10.3
wcwidth               0.1.9
websocket-client      0.59.0
Werkzeug              1.0.1
wheel                 0.36.2
zipp                  3.4.1
```

**To Reproduce**

```
import awswrangler as wr
import boto3
import pandas as pd
from io import BytesIO, StringIO

bucket = 'mybucket'
prefix = 'awswrangler-csv-test/'

df = pd.DataFrame([{'a': 1, 'b': 2}, {'a': 3, 'b': 4}])

# save as CSV
client = boto3.client('s3')
client.put_object(
        Body=df.to_csv(index=False).encode(),
        Bucket=bucket,
        Key=prefix + f'data1.csv',
)
with BytesIO() as b:
    df.to_csv(b, compression='gzip', index=False)
    client.put_object(
        Body=b.getvalue(),
        Bucket=bucket,
        Key=prefix + f'data2.csv.gz',
    )

# read just the uncompressed file, filename exactly
df2 = wr.s3.read_csv(f"s3://{bucket}/{prefix}data1.csv")
assert (df2 == df).all().all()

# read just the uncompressed file, prefix not exact filename
df2 = wr.s3.read_csv(f"s3://{bucket}/{prefix}data1")
assert (df2 == df).all().all()


# read just the compressed file, filename exactly
df2 = wr.s3.read_csv(f"s3://{bucket}/{prefix}data2.csv.gz")
assert (df2 == df).all().all()

# read just the compressed file, prefix not exact filename
df2 = wr.s3.read_csv(f"s3://{bucket}/{prefix}data2")
assert (df2 == df).all().all()

# read both files in one go
df2 = wr.s3.read_csv(f"s3://{bucket}/{prefix}")
assert (df2 == df).all().all()
```

Expected behavior:
Script runs without throwing exceptions.
awswrangler is smart enought to know that it should decompress `data2.csv.gz` and not decompress `data1.csv`.

Actual behavior:
Second-last line fails with:

```
Traceback (most recent call last):
  File "mwe.py", line 44, in <module>
    df2 = wr.s3.read_csv(f"s3://{bucket}/{prefix}")
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/awswrangler/s3/_read_text.py", line 310, in read_csv
    **pandas_kwargs,
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/awswrangler/s3/_read_text.py", line 159, in _read_text
    kwargs=args,
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/awswrangler/s3/_read.py", line 145, in _read_dfs_from_multiple_paths
    return list(df for df in executor.map(partial_read_func, paths, versions))
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/awswrangler/s3/_read.py", line 145, in <genexpr>
    return list(df for df in executor.map(partial_read_func, paths, versions))
  File "/usr/lib64/python3.7/concurrent/futures/_base.py", line 598, in result_iterator
    yield fs.pop().result()
  File "/usr/lib64/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/usr/lib64/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib64/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/awswrangler/s3/_read_text.py", line 91, in _read_text_file
    df: pd.DataFrame = parser_func(f, **pandas_kwargs)
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/cloudshell-user/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 69, in __init__
    self._reader = parsers.TextReader(self.handles.handle, **kwds)
  File "pandas/_libs/parsers.pyx", line 542, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 642, in pandas._libs.parsers.TextReader._get_header
  File "pandas/_libs/parsers.pyx", line 843, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1917, in pandas._libs.parsers.raise_parser_error
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

**Comment by jaidisido** [comment]
This is too specific of a use case IMO as in most cases the underlying prefix will have either `.csv` or `.csv.gz` files but not both. Feel free to contribute with a PR
