### ISSUE TITLE
workgroup not handled correctly in athena.read_sql_query with unload_approach=True

### ISSUE THREAD

**Issue by lucasmo** [awslabs/aws-data-wrangler#1202]
### Describe the bug

When using `unload_approach=True`, the workgroup argument is not respected. No workgroup is utilized when calling boto3, so the workgroup is always primary.

This is because `_resolve_query_without_cache` does not pass a workgroup argument to `_resolve_query_without_cache_unload`, which does not pass a workgroup argument to `_unload`, which has no workgroup argument specified when calling `_start_query_execution`.

### How to Reproduce

```
awswrangler.athena.read_sql_query(
  database='db', 
  sql='select * from db.table limit 10', 
  s3_output=f"s3://bucket/athena-query-results/unload-test-{str(uuid.uuid4())}/", 
  ctas_approach=False, 
  unload_approach=True, 
  workgroup='notprimary'
)
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
File "/path/scratch/aws-wrangler-test/wrangley/lib/python3.9/site-packages/awswrangler/_config.py", line 450, in wrapper
  return function(**args)
File "/path/scratch/aws-wrangler-test/wrangley/lib/python3.9/site-packages/awswrangler/athena/_read.py", line 897, in read_sql_query
  return _resolve_query_without_cache(
File "/path/scratch/aws-wrangler-test/wrangley/lib/python3.9/site-packages/awswrangler/athena/_read.py", line 499, in _resolve_query_without_cache
  return _resolve_query_without_cache_unload(
File "/path/scratch/aws-wrangler-test/wrangley/lib/python3.9/site-packages/awswrangler/athena/_read.py", line 362, in _resolve_query_without_cache_unload
  query_metadata = _unload(
File "/path/scratch/aws-wrangler-test/wrangley/lib/python3.9/site-packages/awswrangler/athena/_read.py", line 578, in _unload
  raise ex
File "/path/scratch/aws-wrangler-test/wrangley/lib/python3.9/site-packages/awswrangler/athena/_read.py", line 563, in _unload
  query_id: str = _start_query_execution(
File "/path/scratch/aws-wrangler-test/wrangley/lib/python3.9/site-packages/awswrangler/athena/_utils.py", line 97, in _start_query_execution
  response: Dict[str, Any] = _utils.try_it(
File "/path/scratch/aws-wrangler-test/wrangley/lib/python3.9/site-packages/awswrangler/_utils.py", line 335, in try_it
  return f(**kwargs)
File "/path/scratch/aws-wrangler-test/wrangley/lib/python3.9/site-packages/botocore/client.py", line 395, in _api_call
  return self._make_api_call(operation_name, kwargs)
File "/path/scratch/aws-wrangler-test/wrangley/lib/python3.9/site-packages/botocore/client.py", line 725, in _make_api_call
  raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the StartQueryExecution operation: User: arn:aws:sts::12345678:assumed-role/A-Role is not authorized to perform: athena:StartQueryExecution on resource: arn:aws:athena:us-east-1:12345678:workgroup/primary with an explicit deny in an identity-based policy
```

### Expected behavior

workgroup argument would be passed to boto3 StartQueryExecution call.

### OS

Mac and Linux

### Python version

3.9

### AWS DataWrangler version

2.14.0

**Comment by lucasmo** [comment]
I went to fix this and realized it's been fixed by #1178. Please note as a duplicate.
