### ISSUE TITLE
[ERROR] UndetectedType: Impossible to infer the equivalent Athena data type for the body column

### ISSUE THREAD

**Issue by darkknight100** [awslabs/aws-data-wrangler#1211]
### Describe the bug

After using the function `awswrangler.catalog.extract_athena_types(df=df, index=False)` following error is prodcued:
```
[ERROR] UndetectedType: Impossible to infer the equivalent Athena data type for the body column. It is completely empty (only null values) and has a too generic data type (object). Please, cast this columns with a more deterministic data type (e.g. df['body'] = df['body'].astype('string')) or pass the column schema as argument for AWS Data Wrangler (e.g. dtype={'body': 'string'}Traceback (most recent call last):  File "/var/task/lambda_handler.py", line 38, in lambda_handler    columns_types, partitions_types = crawl_file(s3_path)  File "/var/task/lambda_handler.py", line 53, in crawl_file    columns_types, partitions_types = wr.catalog.extract_athena_types(  File "/opt/python/awswrangler/catalog/_utils.py", line 285, in extract_athena_types    return _data_types.athena_types_from_pandas_partitioned(  File "/opt/python/awswrangler/_data_types.py", line 555, in athena_types_from_pandas_partitioned    athena_columns_types: Dict[str, str] = athena_types_from_pandas(  File "/opt/python/awswrangler/_data_types.py", line 530, in athena_types_from_pandas    raise exceptions.UndetectedType( | [ERROR] UndetectedType: Impossible to infer the equivalent Athena data type for the body column. It is completely empty (only null values) and has a too generic data type (object). Please, cast this columns with a more deterministic data type (e.g. df['body'] = df['body'].astype('string')) or pass the column schema as argument for AWS Data Wrangler (e.g. dtype={'body': 'string'} Traceback (most recent call last):   File "/var/task/lambda_handler.py", line 38, in lambda_handler     columns_types, partitions_types = crawl_file(s3_path)   File "/var/task/lambda_handler.py", line 53, in crawl_file     columns_types, partitions_types = wr.catalog.extract_athena_types(   File "/opt/python/awswrangler/catalog/_utils.py", line 285, in extract_athena_types     return _data_types.athena_types_from_pandas_partitioned(   File "/opt/python/awswrangler/_data_types.py", line 555, in athena_types_from_pandas_partitioned     athena_columns_types: Dict[str, str] = athena_types_from_pandas(   File "/opt/python/awswrangler/_data_types.py", line 530, in athena_types_from_pandas     raise exceptions.UndetectedType(
-- | --
```

The variable `df` used above is calculated as 
``` 
df: Union[DataFrame, Iterator[DataFrame]] = awswrangler.s3.read_json(s3_path, lines=True)
```

### How to Reproduce

```
def crawl_file(s3_path: str) -> Tuple[Dict[str, str], Dict[str, str]]:
    logger.info(f"Starting to crawl file: {s3_path}")
    df: Union[DataFrame, Iterator[DataFrame]] = wr.s3.read_json(s3_path, lines=True)
    columns_types: Dict[str, str]
    partitions_types: Dict[str, str]
    columns_types, partitions_types = wr.catalog.extract_athena_types(
        df=df, index=False
    )
    logger.info(f"File crawled successfully: {s3_path}")
    return columns_types, partitions_types
```

### OS

Amazon Linux 2

### Python version

3.9.0

### AWS DataWrangler version

2.13.0

**Comment by jaidisido** [comment]
Hi @darkknight100, what the error is saying is the your column (`body`) is completely empty, thus Wrangler is unable to infer the data type. If you keep reading the error trace, it suggests to `Please, cast this columns with a more deterministic data type (e.g. df['body'] = df['body'].astype('string')) or pass the column schema as argument for AWS Data Wrangler (e.g. dtype={'body': 'string'}`

So you can either cast the column to a given type or pass the `dtype` argument to the [method](https://aws-data-wrangler.readthedocs.io/en/stable/stubs/awswrangler.catalog.extract_athena_types.html#awswrangler.catalog.extract_athena_types)
