### ISSUE TITLE
Glue Python Shell botocore and s3transfer incompatible

### ISSUE THREAD

**Issue by rchalmers-te** [awslabs/aws-data-wrangler#1404]
Hello,

When I try to use this on a glue Python Shell job I am getting the following error about botocore and s3transfer being incompatible. Is this something on my end causing this? I am using version 2.14.0

ERROR: awscli 1.16.242 has requirement botocore==1.12.232, but you'll have botocore 1.26.10 which is incompatible.
ERROR: awscli 1.16.242 has requirement s3transfer<0.3.0,>=0.2.0, but you'll have s3transfer 0.5.2 which is incompatible.
WARNING: You are using pip version 20.1; however, version 21.3.1 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "/tmp/runscript.py", line 211, in <module>
    runpy.run_path(temp_file_path, run_name='__main__')
  File "/usr/local/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/local/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/glue-python-scripts-emj6t12f/update_account_landing_metadata.py", line 11, in <module>
  File "/glue/lib/installation/awswrangler/_config.py", line 450, in wrapper
    return function(**args)
  File "/glue/lib/installation/awswrangler/s3/_write_parquet.py", line 911, in store_parquet_metadata
    catalog_id=catalog_id,
  File "/glue/lib/installation/awswrangler/_config.py", line 450, in wrapper
    return function(**args)
  File "/glue/lib/installation/awswrangler/catalog/_create.py", line 801, in create_parquet_table
    catalog_table_input=catalog_table_input,
  File "/glue/lib/installation/awswrangler/catalog/_create.py", line 322, in _create_parquet_table
    catalog_id=catalog_id,
  File "/glue/lib/installation/awswrangler/catalog/_create.py", line 145, in _create_table
    delete_all_partitions(table=table, database=database, catalog_id=catalog_id, boto3_session=session)
  File "/glue/lib/installation/awswrangler/_config.py", line 450, in wrapper
    return function(**args)
  File "/glue/lib/installation/awswrangler/catalog/_delete.py", line 185, in delete_all_partitions
    _get_partitions(database=database, table=table, boto3_session=session, catalog_id=catalog_id).values()
  File "/glue/lib/installation/awswrangler/catalog/_get.py", line 93, in _get_partitions
    response: Dict[str, Any] = client_glue.get_partitions(**args)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 634, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 682, in _convert_to_request_dict
    api_params, operation_model)
  File "/usr/local/lib/python3.6/site-packages/botocore/validate.py", line 297, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in input: "ExcludeColumnSchema", must be one of: CatalogId, DatabaseName, TableName, Expression, NextToken, Segment, MaxResults

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/runscript.py", line 230, in <module>
    raise e_type(e_value).with_traceback(new_stack)
TypeError: __init__() takes 1 positional argument but 2 were given

**Comment by malachi-constant** [comment]
Hi @rchalmers-te are you able to share the snippet from `File "/tmp/runscript.py", line 211, in` I'd like to see if we can understand why we are getting the exception: `Unknown parameter in input: "ExcludeColumnSchema", must be one of: CatalogId, DatabaseName, TableName, Expression, NextToken, Segment, MaxResults`

**Comment by rchalmers-te** [comment]
Thanks for getting back to me @malachi-constant ! Turns out the problem was in the way I was calling one of the data wrangler functions. The log ended up pointing me in the wrong direction. Got it sorted now.

**Comment by josemfsantos97** [comment]
Hello @rchalmers-te, could you please elaborate a bit on what was leading the job to throw the error?

I'm currently having the same issue while trying to write to parquet with `mode="overwrite"`.

**Comment by rchalmers-te** [comment]
Hey @josemfsantos97 . So the line that was causing the problem was indeed trying to write to parquet with the overwrite flag set. Specifically it was the function s3.store_parquet_metadata. Unfortunately I don't have a fix to offer you as a quick test using the append flag instead showed that this function wasn't going to solve the problem I was trying to solve even if I got the overwrite flag working. Sorry I cant be more help.

**Comment by alecbw** [comment]
Just to add to this - I got the same error specifically after updating awswrangler from 1.9.6 to 2.17.0 and Python from 3.7.7 to 3.9.9 -  `botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in input: "ExcludeColumnSchema", must be one of: CatalogId, DatabaseName, TableName, Expression, NextToken, Segment, MaxResults`
