### ISSUE TITLE
An error occurred (404) when calling the HeadObject operation: Not Found

### ISSUE THREAD

**Issue by avanibhatnagar** [awslabs/aws-data-wrangler#213]
I'm using aws-data-wrangler to be able to use pandas to convert a bunch of xls files to csv. I read the documentation and I have the .whl file uploaded to an S3 bucket and added it to Python library path option in the AWS Glue job. 

I am doing a simple conversion of just one file to test:
```
import pandas

read_file = pd.read_excel ('s3://s3foler/../../name_of_file.xls')
read_file.to_csv ('s3://s3folder/../../name_of_file.csv', index = None, header=True)
```

This fails with the following error:
```
Traceback (most recent call last):
  File "/tmp/runscript.py", line 113, in <module>
    download_and_install(args.extra_files)
  File "/tmp/runscript.py", line 55, in download_and_install
    download_from_s3(s3_file_path, local_file_path)
  File "/tmp/runscript.py", line 80, in download_from_s3
    s3.download_file(bucket_name, s3_key, new_file_path)
  File "/usr/local/lib/python3.6/site-packages/boto3/s3/inject.py", line 172, in download_file
    extra_args=ExtraArgs, callback=Callback)
  File "/usr/local/lib/python3.6/site-packages/boto3/s3/transfer.py", line 307, in download_file
    future.result()
  File "/usr/local/lib/python3.6/site-packages/s3transfer/futures.py", line 106, in result
    return self._coordinator.result()
  File "/usr/local/lib/python3.6/site-packages/s3transfer/futures.py", line 265, in result
    raise self._exception
  File "/usr/local/lib/python3.6/site-packages/s3transfer/tasks.py", line 255, in _main
    self._submit(transfer_future=transfer_future, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/s3transfer/download.py", line 345, in _submit
    **transfer_future.meta.call_args.extra_args
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (404) when calling the HeadObject operation: Not Found
```

Not sure why there is a 404 error here.

Any help is appreciated!

**Comment by igorborgest** [comment]
Hi @avanibhatnagar !

Could you please double-check the s3 path on your Job configuration? Seems that Glue is not finding the `.whl` file because it is not even starting the execution itself, this error is happening during the installation step.

**Comment by avanibhatnagar** [comment]
So I've set the s3 path for 'Python Library Path'  to 's3://bucket/sub-folder/awswrangler-1.0.4-py3-none-any.whl'
And the xls and csv files are in another bucket.
The Referenced files path had a value before, but I just removed it to see if that changes anything and now the error is different:
```
Traceback (most recent call last):
  File "/tmp/runscript.py", line 118, in <module>
    runpy.run_path(temp_file_path, run_name='__main__')
  File "/usr/local/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/local/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/glue-python-scripts-8ais4vfg/convert xls to csv.py", line 2, in <module>
ModuleNotFoundError: No module named 'xlrd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/runscript.py", line 137, in <module>
    raise e_type(e_value).with_tracsback(new_stack)
AttributeError: 'ModuleNotFoundError' object has no attribute 'with_tracsback'
```

**Comment by igorborgest** [comment]
@avanibhatnagar, now it is loading the Wrangler correctly.

The your current problem is that Wrangler does not has the `xlrd` embedded yet, so you will need to add its Wheel besides the Wrangler one.

[Here](https://docs.aws.amazon.com/glue/latest/dg/add-job-python.html#create-python-extra-library) is some reference about it.

Btw, the packages embedded on Wrangler are [these ones](https://github.com/awslabs/aws-data-wrangler/blob/master/requirements.txt) by now.

**Comment by avanibhatnagar** [comment]
Thanks for that explanation! Just an additional question - I am unable to add another Wheel for xlrd since I already have the Wheel for Wrangler in the 'Python Library Path'.

**Comment by igorborgest** [comment]
@avanibhatnagar just add another path separated by comma. 😊

**Comment by avanibhatnagar** [comment]
Ok so now I have both the wheel files but I'm still stuck at something else but it's unrelated to Wrangler I think - would GREATLY appreciate if you could give me any suggestions!

```
Traceback (most recent call last):
  File "/tmp/runscript.py", line 117, in <module>
    download_and_install(args.extra_py_files)
  File "/tmp/runscript.py", line 63, in download_and_install
    subprocess.check_call([sys.executable, "-m", "pip", "install", "--target=
{}
".format(install_path), local_file_path])
  File "/usr/local/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/bin/python', '-m', 'pip', 'install', '--target=/glue/lib/installation', '/tmp/glue-python-libs-1qiis6yj/xlrd-1.2.0-py2.py3-none-any.whl']' returned non-zero exit status 2.
```

**Comment by igorborgest** [comment]
@avanibhatnagar , I'm not sure what is happening on your environment, I just tested both wheels in a job here, and everything went fine.

Python lib path: `s3://bucket/awswrangler-1.0.4-py3-none-any.whl,s3://bucket/xlrd-1.2.0-py2.py3-none-any.whl`

**Comment by igorborgest** [comment]
Closing due to inactivity.
