### ISSUE TITLE
Pyarrow 15 compatability

### ISSUE THREAD

**Issue by schmidt-ai** [awslabs/aws-data-wrangler#2650]
### Describe the bug

Pyarrow 15 breaks awswrangler:
```
Traceback (most recent call last):
  File "...", line 5, in <module>
    from awswrangler.athena import read_sql_query
  File ".../.venv/lib/python3.10/site-packages/awswrangler/__init__.py", line 10, in <module>
    from awswrangler import (  # noqa
  File ".../.venv/lib/python3.10/site-packages/awswrangler/athena/__init__.py", line 3, in <module>
    from awswrangler.athena._executions import (  # noqa
  File ".../.venv/lib/python3.10/site-packages/awswrangler/athena/_executions.py", line 17, in <module>
    from awswrangler import _utils, exceptions, typing
  File ".../.venv/lib/python3.10/site-packages/awswrangler/_utils.py", line 40, in <module>
    from awswrangler._arrow import _table_to_df
  File ".../.venv/lib/python3.10/site-packages/awswrangler/_arrow.py", line 12, in <module>
    from awswrangler._data_types import athena2pyarrow
  File ".../.venv/lib/python3.10/site-packages/awswrangler/_data_types.py", line 695, in <module>
    partitions: Optional[pyarrow.parquet.ParquetPartitions],
AttributeError: module 'pyarrow.parquet' has no attribute 'ParquetPartitions'
```

### How to Reproduce

```sh
pip install -U pyarrow==15
```

```python
from awswrangler.athena import read_sql_query
```

### OS

Darwin

### Python version

3.10.13

### AWS SDK for pandas version

3.5.2

**Comment by jlondonobo** [comment]
Hey @schmidt-ai, came looking for the same thing! I believe it was solved in #2649.
