### ISSUE TITLE
pyarrow/parquet exception (only when running on lambda)

### ISSUE THREAD

**Issue by jesusch** [awslabs/aws-data-wrangler#277]
**Describe the bug**

given the following code: 
```python
pq_file = f's3://{bucket}/{client}/{brand}/yy={year:04d}/mm={month:02d}/dd={day:02d}/{client}-{brand}-spots-{year:04d}-{month:02d}-{day:02d}.snappy.parquet'
df = wr.s3.read_parquet(path=[pq_file])
```

On AWS Lambda (1.3.0 and 1.4.0) I get the following exception:
```
[ERROR] OSError: Passed non-file path: s3://my-bucket/1337/1/spots/yy=2020/mm=05/dd=05/bigfile.snappy.parquet
Traceback (most recent call last):
  File "/var/task/handler.py", line 80, in getOrdinals
    df = wr.s3.read_parquet(path=[pq_file])
  File "/opt/python/awswrangler/s3.py", line 1851, in read_parquet
    data: pyarrow.parquet.ParquetDataset = _read_parquet_init(
  File "/opt/python/awswrangler/s3.py", line 1727, in _read_parquet_init
    data: pyarrow.parquet.ParquetDataset = pyarrow.parquet.ParquetDataset(
  File "/opt/python/pyarrow/parquet.py", line 1171, in __init__
    self.metadata_path) = _make_manifest(
  File "/opt/python/pyarrow/parquet.py", line 1367, in _make_manifest
    raise OSError('Passed non-file path: {}')
```

On my local machine (python:3.7.7, pyarrow:0.17.1, s3fs:0.4.2, awswrangler:1.4.0) I don't get this exception?

**Comment by igorborgest** [comment]
Hi @jesusch !

I've noticed that your path in the code differ from the one in the exception. For example, the file name is totally different.

Is it really happening, or is only for the sake of the exemplification?

In addition to that, are you sure that the lambda role has all privileges enough on s3?

**Comment by igorborgest** [comment]
Closing due to inactivity.
