### ISSUE TITLE
Reading an SQL Query from Athena raises an error if data contains NaN values

### ISSUE THREAD

**Issue by czagoni** [awslabs/aws-data-wrangler#351]
**Describe the bug**

In case there are `NaN` values in the table produced by an Athena SQL Query, reading it with `awswrangler.athena.read_sql_query(..., ctas_approach=False)` throws an exception.

**To Reproduce**

python version: 3.7.6 64-bit
awswrangler version: 1.8.0 

As a simple example let's take an Athena SQL Query that produces a table with column `X` containing `NaN` values (e.g. due to division by zero).  
When this table is exported to a `csv` file, `NaN` values are represented by "NaN" strings (i.e. different to NULL values which are represented by "" (empty) strings).

`awswrangler.athena.read_sql_query()` called with `ctas_approach=False` raises:

```
TypeError: Cannot cast array data from dtype('O') to dtype('float64') according to the rule 'safe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runner.py", line 35, in <module>
    }, {})
  File "/Users/quarentine/dev/upside/ami-reports/report-generators/athena-report-generator/src/aws.py", line 19, in lambda_handler
    reportGenerator.generate_report(request)
  File "/Users/quarentine/.virtualenvs/ami-report-generators/lib/python3.7/site-packages/aws_embedded_metrics/metric_scope/__init__.py", line 46, in wrapper
    raise e
  File "/Users/quarentine/.virtualenvs/ami-report-generators/lib/python3.7/site-packages/aws_embedded_metrics/metric_scope/__init__.py", line 44, in wrapper
    return fn(*args, **kwargs)
  File "/Users/quarentine/dev/upside/ami-reports/report-generators/athena-report-generator/src/app.py", line 84, in generate_report
    df = wr.athena.read_sql_query(query, database=self._database_name, ctas_approach=False)
  File "/Users/quarentine/dev/upside/ami-reports/report-generators/aws-data-wrangler/awswrangler/_config.py", line 263, in wrapper
    return function(**args)
  File "/Users/quarentine/dev/upside/ami-reports/report-generators/aws-data-wrangler/awswrangler/athena/_read.py", line 700, in read_sql_query
    boto3_session=session,
  File "/Users/quarentine/dev/upside/ami-reports/report-generators/aws-data-wrangler/awswrangler/athena/_read.py", line 504, in _resolve_query_without_cache
    boto3_session=boto3_session,
  File "/Users/quarentine/dev/upside/ami-reports/report-generators/aws-data-wrangler/awswrangler/athena/_read.py", line 441, in _resolve_query_without_cache_regular
    boto3_session=boto3_session,
  File "/Users/quarentine/dev/upside/ami-reports/report-generators/aws-data-wrangler/awswrangler/athena/_read.py", line 273, in _fetch_csv_result
    boto3_session=boto3_session,
  File "/Users/quarentine/dev/upside/ami-reports/report-generators/aws-data-wrangler/awswrangler/s3/_read_text.py", line 265, in read_csv
    **pandas_kwargs,
  File "/Users/quarentine/dev/upside/ami-reports/report-generators/aws-data-wrangler/awswrangler/s3/_read_text.py", line 128, in _read_text
    ret = _read_text_file(path=paths[0], **args)
  File "/Users/quarentine/dev/upside/ami-reports/report-generators/aws-data-wrangler/awswrangler/s3/_read_text.py", line 77, in _read_text_file
    df: pd.DataFrame = parser_func(f, **pandas_kwargs)
  File "/Users/quarentine/.virtualenvs/ami-report-generators/lib/python3.7/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/Users/quarentine/.virtualenvs/ami-report-generators/lib/python3.7/site-packages/pandas/io/parsers.py", line 454, in _read
    data = parser.read(nrows)
  File "/Users/quarentine/.virtualenvs/ami-report-generators/lib/python3.7/site-packages/pandas/io/parsers.py", line 1133, in read
    ret = self._engine.read(nrows)
  File "/Users/quarentine/.virtualenvs/ami-report-generators/lib/python3.7/site-packages/pandas/io/parsers.py", line 2037, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 860, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 875, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 952, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 1084, in pandas._libs.parsers.TextReader._convert_column_data
  File "pandas/_libs/parsers.pyx", line 1160, in pandas._libs.parsers.TextReader._convert_tokens
ValueError: cannot safely convert passed user dtype of float64 for object dtyped data in column 2
```

It looks like in `_fetch_csv_result()` the `query_metadata.dtype` dict holds a dtype of `float64` for column 'X' 

However, as `s3.read_csv()` is called with `keep_default_na=False, na_values=[""],` args, the "NaN" strings are not mapped to `NaN` values during the read, the resulting dtype of column 'X' is therefore a `string` which conflicts with the dtype dict passed in by `dtype=query_metadata.dtype` - hence the exception being raised by pandas.

One possible fix, that worked for us would be to add the "NaN" string to the `s3.read_csv` arguments i.e. 
`keep_default_na=False, na_values=["", "NaN"],`
in case that does not cause any side-effects (or have these pandas kwargs parameterised instead of hardcoded).

**Comment by igorborgest** [comment]
Thanks @czagoni. Good catch and awesome troubleshooting!

I've just fixed the issue in our `dev` branch through the commit above and I also took the opportunity to cover Athena `Inifity` values with tests for both `ctas_approach` options.

Do you mind to test it and check if it solves your use case?
The ideia is to publish this fix in the version `1.8.1` later today.

```sh
pip install git+https://github.com/awslabs/aws-data-wrangler.git@dev
```

**Comment by czagoni** [comment]
Thanks @igorborgest for the insanely fast fix! 
I can confirm this solved the issue for our use case.
;)

**Comment by igorborgest** [comment]
Release in version [1.8.1](https://github.com/awslabs/aws-data-wrangler/releases/tag/1.8.1)

**Comment by igorborgest** [comment]
@czagoni 

It is totally off-topic, but we are stating a [_"Who uses AWS Data Wrangler?"_](https://github.com/awslabs/aws-data-wrangler/tree/dev#who-uses-aws-data-wrangler) section. So feel free to add yourself if you want 😄 .
