### ISSUE TITLE
s3 path result from  catalog.get_table_location is not suffice for db.copy_files_to_redshift

### ISSUE THREAD

**Issue by tuannguyen0901** [awslabs/aws-data-wrangler#401]
**Describe the bug**
s3 path resulted from get_table_location does not work with copy_files_to_Redshift()
the table have partition.

**To Reproduce**
clean_s3_path = wr.catalog.get_table_location(database=clean_database, table=clean_table)
wr.db.copy_files_to_redshift(
    path=clean_s3_path,
    manifest_directory = clean_s3_path,
    con=engine,
    table="my_table",
    schema="mtproduction",
    iam_role="arn:aws:iam::xxx:role/xxx"
)

**Error log**
`Traceback (most recent call last):
  File "/home/ec2-user/environment/Untitled1.py", line 33, in <module>
  File "/usr/local/lib/python3.6/site-packages/awswrangler/db.py", line 907, in copy_files_to_redshift
    path=paths, sampling=parquet_infer_sampling, dataset=False, use_threads=use_threads, boto3_session=session
  File "/usr/local/lib/python3.6/site-packages/awswrangler/_config.py", line 263, in wrapper
    return function(**args)
  File "/usr/local/lib/python3.6/site-packages/awswrangler/s3/_read_parquet.py", line 795, in read_parquet_metadata
    boto3_session=_utils.ensure_session(session=boto3_session),
  File "/usr/local/lib/python3.6/site-packages/awswrangler/s3/_read_parquet.py", line 150, in _read_parquet_metadata
    s3_additional_kwargs=s3_additional_kwargs,
  File "/usr/local/lib/python3.6/site-packages/awswrangler/s3/_read_parquet.py", line 76, in _read_schemas_from_files
    itertools.repeat(use_threads),
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/awswrangler/s3/_read_parquet.py", line 46, in _read_parquet_metadata_file
    pq_file: pyarrow.parquet.ParquetFile = pyarrow.parquet.ParquetFile(source=f)
  File "/usr/local/lib64/python3.6/site-packages/pyarrow/parquet.py", line 200, in __init__
    read_dictionary=read_dictionary, metadata=metadata)
  File "pyarrow/_parquet.pyx", line 1020, in pyarrow._parquet.ParquetReader.open
  File "pyarrow/error.pxi", line 84, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Parquet magic bytes not found in footer. Either the file is corrupted or this is not a parquet file.`

**Comment by tuannguyen0901** [comment]
Traceback (most recent call last):
  File "/home/ec2-user/environment/Untitled1.py", line 33, in <module>
    iam_role="arn:aws:iam::895454937133:role/awsglue"
  File "/usr/local/lib/python3.6/site-packages/awswrangler/db.py", line 907, in copy_files_to_redshift
    path=paths, sampling=parquet_infer_sampling, dataset=False, use_threads=use_threads, boto3_session=session
  File "/usr/local/lib/python3.6/site-packages/awswrangler/_config.py", line 263, in wrapper
    return function(**args)
  File "/usr/local/lib/python3.6/site-packages/awswrangler/s3/_read_parquet.py", line 795, in read_parquet_metadata
    boto3_session=_utils.ensure_session(session=boto3_session),
  File "/usr/local/lib/python3.6/site-packages/awswrangler/s3/_read_parquet.py", line 150, in _read_parquet_metadata
    s3_additional_kwargs=s3_additional_kwargs,
  File "/usr/local/lib/python3.6/site-packages/awswrangler/s3/_read_parquet.py", line 76, in _read_schemas_from_files
    itertools.repeat(use_threads),
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/awswrangler/s3/_read_parquet.py", line 46, in _read_parquet_metadata_file
    pq_file: pyarrow.parquet.ParquetFile = pyarrow.parquet.ParquetFile(source=f)
  File "/usr/local/lib64/python3.6/site-packages/pyarrow/parquet.py", line 200, in __init__
    read_dictionary=read_dictionary, metadata=metadata)
  File "pyarrow/_parquet.pyx", line 1020, in pyarrow._parquet.ParquetReader.open
  File "pyarrow/error.pxi", line 84, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Parquet magic bytes not found in footer. Either the file is corrupted or this is not a parquet file.

**Comment by Jahn-KSB** [comment]
could you fix this? @tuannguyen0901
