### ISSUE TITLE
Excel files support

### ISSUE THREAD

**Issue by tochandrashekhar** [awslabs/aws-data-wrangler#419]
we are reading excel file in pandas and writing to csv via wrangler .It was working fine till awswrangler-1.8.1.
but new version of wrangler has removed s3fs dependency , our job is failing while reading excel file.

We tried to add s3fs-0.5.1-py3-none-any.whl as external library but Still getting below error.
ImportError: cannot import name 'S3ArnParamHandler
 

Traceback (most recent call last):  File "/tmp/runscript.py", line 142, in <module>    raise e_type(e_value).with_traceback(new_stack)  File "/tmp/glue-python-scripts-hzeysn4_/exceltocsv.py", line 5, in <module>  File "/glue/lib/installation/s3fs/__init__.py", line 1, in <module>    from .core import S3FileSystem, S3File  File "/glue/lib/installation/s3fs/core.py", line 14, in <module>    import aiobotocore  File "/glue/lib/installation/aiobotocore/__init__.py", line 1, in <module>    from .session import get_session, AioSession  File "/glue/lib/installation/aiobotocore/session.py", line 6, in <module>    from .client import AioClientCreator, AioBaseClient  File "/glue/lib/installation/aiobotocore/client.py", line 2, in <module>    from botocore.client import logger, PaginatorDocstring, ClientCreator, \ImportError: cannot import name 'S3ArnParamHandler' | Traceback (m
-- | --

**Comment by tochandrashekhar** [comment]
@igorborgest  I want to thank you for such wonderful product. 
Please do not delay support for  excel file.

**Comment by igorborgest** [comment]
Released on version [2.3.0](https://github.com/awslabs/aws-data-wrangler/releases/tag/2.3.0) 🚀
