### ISSUE TITLE
Issue on try to connect to redshift

### ISSUE THREAD

**Issue by rubenssoto** [awslabs/aws-data-wrangler#517]
Hello,

I'm trying to connect to redshift using secrets manager and I got an error:

import awswrangler as wr

con = wr.redshift.connect(secret_id='secret full arn')

`You must specify a region.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/awswrangler/redshift.py", line 386, in connect
    connection=connection, secret_id=secret_id, catalog_id=catalog_id, dbname=dbname, boto3_session=boto3_session
  File "/usr/local/lib/python3.7/site-packages/awswrangler/_databases.py", line 94, in get_connection_attributes
    secret_id=cast(str, secret_id), dbname=dbname, boto3_session=boto3_session
  File "/usr/local/lib/python3.7/site-packages/awswrangler/_databases.py", line 57, in _get_connection_attributes_from_secrets_manager
    secret_value: Dict[str, Any] = secretsmanager.get_secret_json(name=secret_id, boto3_session=boto3_session)
  File "/usr/local/lib/python3.7/site-packages/awswrangler/secretsmanager.py", line 67, in get_secret_json
    value: Union[str, bytes] = get_secret(name=name, boto3_session=boto3_session)
  File "/usr/local/lib/python3.7/site-packages/awswrangler/secretsmanager.py", line 38, in get_secret
    client: boto3.client = _utils.client(service_name="secretsmanager", session=session)
  File "/usr/local/lib/python3.7/site-packages/awswrangler/_utils.py", line 95, in client
    config=botocore_config() if config is None else config,
  File "/usr/local/lib/python3.7/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/lib/python3.7/site-packages/botocore/session.py", line 838, in create_client
    client_config=config, api_version=api_version)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 87, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 328, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/lib/python3.7/site-packages/botocore/args.py", line 73, in get_client_args
    endpoint_url, is_secure, scoped_config)
  File "/usr/local/lib/python3.7/site-packages/botocore/args.py", line 153, in compute_client_args
    s3_config=s3_config,
  File "/usr/local/lib/python3.7/site-packages/botocore/args.py", line 218, in _compute_endpoint_config
    return self._resolve_endpoint(**resolve_endpoint_kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/args.py", line 301, in _resolve_endpoint
    service_name, region_name, endpoint_url, is_secure)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 402, in resolve
    service_name, region_name)
  File "/usr/local/lib/python3.7/site-packages/botocore/regions.py", line 134, in construct_endpoint
    partition, service_name, region_name)
  File "/usr/local/lib/python3.7/site-packages/botocore/regions.py", line 148, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.`

could you help me?

Thank you

**Comment by igorborgest** [comment]
Seems you don't have a REGION configured in your environment and this is something boto3 and Wrangler requires.
There are some ways to do that like exporting `AWS_DEFAULT_REGION` as environment variable for example.

But let me show how to do it programmatically instead:

```py3
import boto3
import awswrangler as wr

boto3.setup_default_session(region_name="us-east-1")
con = wr.redshift.connect(secret_id='secret full arn')
```

Or if you prefer to handle you own boto3 session instead of use the default one:

```py3
import boto3
import awswrangler as wr

my_session = boto3.Session(region_name="us-east-1")
con = wr.redshift.connect(secret_id='secret full arn', boto3_session=my_session)

```

**Comment by igorborgest** [comment]
closed due inactivity.
