### ISSUE TITLE
Using awswrangler 2.4.0 with glue 2.0 in --additional-python-modules results in Error

### ISSUE THREAD

**Issue by nikwerhypoport** [awslabs/aws-data-wrangler#547]
**Describe the bug**
Using awswrangler 2.4.0 with glue 2.0 in --additional-python-modules results in Error.
In an GlueJob error log, I find the message ` OSError: 'git' was not found  `

**To Reproduce**
- create a glue Py Spark Job with a py script and Glue Version 2.0
- inside the script, I have `import awswrangler as aw`
- the Job has parameter `--additional-python-modules awswrangler`
- I run the Job
- Job fails with `no module named awswrangler` 
- so far I can see, this did not happen with Version 2.3.0
- Workaround so far
   - pinning the version to 2.3.0 with `--additional-python-modules awswrangler==2.3.0`

CloudWatch ErrorLog in Detail:
```
INFO	2021-02-04 08:12:53,574	9223	com.amazonaws.services.glue.PythonModuleInstaller	[main]	Collecting awswrangler  Downloading https://files.pythonhosted.org/packages/28/57/debf8f714d5b1a14ce39a6e8bbd1105beaab8490f96c2673fe04bf27cedb/awswrangler-2.4.0-py3-none-any.whl (171kB)Collecting botocore<2.0.0,>=1.15.49 (from awswrangler)  Downloading https://files.pythonhosted.org/packages/f7/d1/35591aa624c5f450e32eab12fec2b03ad51b7ad656b7fa17acf04b474372/botocore-1.20.1-py2.py3-none-any.whl (7.2MB)Requirement already satisfied: numpy<1.21.0,>=1.18.0 in /home/spark/.local/lib/python3.7/site-packages (from awswrangler)Collecting pg8000<1.18.0,>=1.16.0 (from awswrangler)  Downloading https://files.pythonhosted.org/packages/ed/d9/2a20d2f41d59b7b814f7cb30e8df9bbd288b000ad8a04dbc97d8c92df6df/pg8000-1.17.0-py3-none-any.whlRequirement already satisfied: pymysql<1.1.0,>=0.9.0 in /home/spark/.local/lib/python3.7/site-packages (from awswrangler)Collecting openpyxl~=3.0.0 (from awswrangler)  Downloading https://files.pythonhosted.org/packages/d4/c5/1a5f82b3020bfb27f21b302f96c8ae6a34475070015d1b1e0b197a97e2af/openpyxl-3.0.6-py2.py3-none-any.whl (242kB)Collecting redshift-connector~=2.0.0 (from awswrangler)  Downloading https://files.pythonhosted.org/packages/9a/87/ad4bdda8037bc1e1c36c227309a48321b2c6faaf6b01328a7341738e7424/redshift_connector-2.0.873-py3-none-any.whl (80kB)Collecting pyarrow<3.1.0,>=2.0.0 (from awswrangler)  Downloading https://files.pythonhosted.org/packages/62/d3/a482d8a4039bf931ed6388308f0cc0541d0cab46f0bbff7c897a74f1c576/pyarrow-3.0.0.tar.gz (682kB)    Complete output from command python setup.py egg_info:    Traceback (most recent call last):      File "<string>", line 1, in <module>      File "/tmp/pip-build-3qfyk1xp/pyarrow/setup.py", line 624, in <module>        url='https://arrow.apache.org/'      File "/home/spark/.local/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup        return distutils.core.setup(**attrs)      File "/usr/lib64/python3.7/distutils/core.py", line 108, in setup        _setup_distribution = dist = klass(attrs)      File "/home/spark/.local/lib/python3.7/site-packages/setuptools/dist.py", line 448, in __init__        k: v for k, v in attrs.items()      File "/usr/lib64/python3.7/distutils/dist.py", line 292, in __init__        self.finalize_options()      File "/home/spark/.local/lib/python3.7/site-packages/setuptools/dist.py", line 740, in finalize_options        ep.load()(self)      File "/home/spark/.local/lib/python3.7/site-packages/setuptools/dist.py", line 747, in _finalize_setup_keywords        ep.load()(self, ep.name, value)      File "/tmp/pip-build-3qfyk1xp/pyarrow/.eggs/setuptools_scm-5.0.1-py3.7.egg/setuptools_scm/integration.py", line 26, in version_keyword        dist.metadata.version = _get_version(config)      File "/tmp/pip-build-3qfyk1xp/pyarrow/.eggs/setuptools_scm-5.0.1-py3.7.egg/setuptools_scm/__init__.py", line 173, in _get_version        parsed_version = _do_parse(config)      File "/tmp/pip-build-3qfyk1xp/pyarrow/.eggs/setuptools_scm-5.0.1-py3.7.egg/setuptools_scm/__init__.py", line 119, in _do_parse        parse_result = _call_entrypoint_fn(config.absolute_root, config, config.parse)      File "/tmp/pip-build-3qfyk1xp/pyarrow/.eggs/setuptools_scm-5.0.1-py3.7.egg/setuptools_scm/__init__.py", line 54, in _call_entrypoint_fn        return fn(root)      File "/tmp/pip-build-3qfyk1xp/pyarrow/setup.py", line 542, in parse_git        return parse(root, **kwargs)      File "/tmp/pip-build-3qfyk1xp/pyarrow/.eggs/setuptools_scm-5.0.1-py3.7.egg/setuptools_scm/git.py", line 95, in parse        require_command("git")      File "/tmp/pip-build-3qfyk1xp/pyarrow/.eggs/setuptools_scm-5.0.1-py3.7.egg/setuptools_scm/utils.py", line 151, in require_command        raise EnvironmentError("%r was not found" % name)    OSError: 'git' was not found        ----------------------------------------
```

**Comment by igorborgest** [comment]
Hi @nikwerhypoport , thanks for reporting it.

**For platforms without PyArrow 3 support (e.g. [EMR](https://aws-data-wrangler.readthedocs.io/en/latest/install.html#emr-cluster)):**

`pip install pyarrow==2 awswrangler`

Or specifically for [Glue PySpark Job](https://aws-data-wrangler.readthedocs.io/en/latest/install.html#aws-glue-pyspark-jobs):

- **Key:** `--additional-python-modules`
   **Value:** `pyarrow==2,awswrangler`

**Comment by igorborgest** [comment]
P.S. Also consider to freeze the Wrangler version for productive environments (e.g. `awswrangler==2.3.0`)

**Comment by nikwerhypoport** [comment]
> P.S. Also consider to freeze the Wrangler version for productive environments (e.g. `awswrangler==2.3.0`)

- tested it successfully with `--additional-python-modules pyarrow==2,awswrangler==2.4.0`
- so I have the opportunity to use 2.4.0 features already and can wait, until the arrow issue is fixed in future 
Thx
