### ISSUE TITLE
Error on dependency installation

### ISSUE THREAD

**Issue by rubenssoto** [awslabs/aws-data-wrangler#549]
Hello,

I use aws data wrangler in my emr clusters, today I started to have some bootstrap problems with data wrangler, could you help me?

```
Collecting awswrangler
  Downloading https://files.pythonhosted.org/packages/28/57/debf8f714d5b1a14ce39a6e8bbd1105beaab8490f96c2673fe04bf27cedb/awswrangler-2.4.0-py3-none-any.whl (171kB)
Requirement already satisfied: pandas<1.3.0,>=1.1.0 in /usr/local/lib64/python3.7/site-packages (from awswrangler)
Requirement already satisfied: boto3<2.0.0,>=1.12.49 in /usr/local/lib/python3.7/site-packages (from awswrangler)
Collecting pyarrow<3.1.0,>=2.0.0 (from awswrangler)
  Downloading https://files.pythonhosted.org/packages/62/d3/a482d8a4039bf931ed6388308f0cc0541d0cab46f0bbff7c897a74f1c576/pyarrow-3.0.0.tar.gz (682kB)
    Complete output from command python setup.py egg_info:
    /usr/lib64/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/mnt/tmp/pip-build-00riuili/pyarrow/setup.py", line 624, in <module>
        url='https://arrow.apache.org/'
      File "/usr/lib/python3.7/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python3.7/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3.7/site-packages/setuptools/dist.py", line 333, in __init__
        _Distribution.__init__(self, attrs)
      File "/usr/lib64/python3.7/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "/usr/lib/python3.7/site-packages/setuptools/dist.py", line 476, in finalize_options
        ep.load()(self, ep.name, value)
      File "/mnt/tmp/pip-build-00riuili/pyarrow/.eggs/setuptools_scm-5.0.1-py3.7.egg/setuptools_scm/integration.py", line 26, in version_keyword
        dist.metadata.version = _get_version(config)
      File "/mnt/tmp/pip-build-00riuili/pyarrow/.eggs/setuptools_scm-5.0.1-py3.7.egg/setuptools_scm/__init__.py", line 173, in _get_version
        parsed_version = _do_parse(config)
      File "/mnt/tmp/pip-build-00riuili/pyarrow/.eggs/setuptools_scm-5.0.1-py3.7.egg/setuptools_scm/__init__.py", line 119, in _do_parse
        parse_result = _call_entrypoint_fn(config.absolute_root, config, config.parse)
      File "/mnt/tmp/pip-build-00riuili/pyarrow/.eggs/setuptools_scm-5.0.1-py3.7.egg/setuptools_scm/__init__.py", line 54, in _call_entrypoint_fn
        return fn(root)
      File "/mnt/tmp/pip-build-00riuili/pyarrow/setup.py", line 542, in parse_git
        return parse(root, **kwargs)
      File "/mnt/tmp/pip-build-00riuili/pyarrow/.eggs/setuptools_scm-5.0.1-py3.7.egg/setuptools_scm/git.py", line 95, in parse
        require_command("git")
      File "/mnt/tmp/pip-build-00riuili/pyarrow/.eggs/setuptools_scm-5.0.1-py3.7.egg/setuptools_scm/utils.py", line 151, in require_command
        raise EnvironmentError("%r was not found" % name)
    OSError: 'git' was not found
    
    ----------------------------------------
```

**Comment by igorborgest** [comment]
Hi @rubenssoto, where are you trying to install?

## FYI

**For platforms without PyArrow 3 support (e.g. [EMR](https://aws-data-wrangler.readthedocs.io/en/latest/install.html#emr-cluster)):**

`pip install pyarrow==2 awswrangler`

Or specifically for [Glue PySpark Job](https://aws-data-wrangler.readthedocs.io/en/latest/install.html#aws-glue-pyspark-jobs):

- **Key:** `--additional-python-modules`
   **Value:** `pyarrow==2,awswrangler`

**Comment by igorborgest** [comment]
We've updated our [EMR install instructions](https://aws-data-wrangler.readthedocs.io/en/2.4.0-docs/install.html#emr-cluster) on the docs.

Also, consider to freeze the Wrangler version in the bootstrap for productive environments (e.g. awswrangler==2.4.0)
