### ISSUE TITLE
ModuleNotFoundError: No module named 'Cython'

### ISSUE THREAD

**Issue by 18vidhyasagar** [awslabs/aws-data-wrangler#578]
Description:
Met with "ModuleNotFoundError: No module named 'Cython'" while trying to install awswrangler==2.4.0 on MWAA (Amazon Managed Airflow)

```
Collecting awswrangler==2.4.0 (from -r /usr/local/airflow/requirements/requirements.txt (line 1))
--
Downloading https://files.pythonhosted.org/packages/28/57/debf8f714d5b1a14ce39a6e8bbd1105beaab8490f96c2673fe04bf27cedb/awswrangler-2.4.0-py3-none-any.whl (171kB)
Requirement already satisfied: boto3<2.0.0,>=1.12.49 in /usr/local/lib/python3.7/site-packages (from awswrangler==2.4.0->-r /usr/local/airflow/requirements/requirements.txt (line 1))
Collecting redshift-connector~=2.0.0 (from awswrangler==2.4.0->-r /usr/local/airflow/requirements/requirements.txt (line 1))
Downloading https://files.pythonhosted.org/packages/75/f1/ae0e04b24198d8841842f37174aad6266d00bebc8f6b9a2ce38796d26ee1/redshift_connector-2.0.874-py3-none-any.whl (81kB)
Requirement already satisfied: pandas<1.3.0,>=1.1.0 in /usr/local/lib64/python3.7/site-packages (from awswrangler==2.4.0->-r /usr/local/airflow/requirements/requirements.txt (line 1))
Requirement already satisfied: botocore<2.0.0,>=1.15.49 in /usr/local/lib/python3.7/site-packages (from awswrangler==2.4.0->-r /usr/local/airflow/requirements/requirements.txt (line 1))
Collecting pg8000<1.18.0,>=1.16.0 (from awswrangler==2.4.0->-r /usr/local/airflow/requirements/requirements.txt (line 1))
Downloading https://files.pythonhosted.org/packages/ed/d9/2a20d2f41d59b7b814f7cb30e8df9bbd288b000ad8a04dbc97d8c92df6df/pg8000-1.17.0-py3-none-any.whl
Requirement already satisfied: numpy<1.21.0,>=1.18.0 in /usr/local/lib64/python3.7/site-packages (from awswrangler==2.4.0->-r /usr/local/airflow/requirements/requirements.txt (line 1))
Collecting pymysql<1.1.0,>=0.9.0 (from awswrangler==2.4.0->-r /usr/local/airflow/requirements/requirements.txt (line 1))
Downloading https://files.pythonhosted.org/packages/4f/52/a115fe175028b058df353c5a3d5290b71514a83f67078a6482cff24d6137/PyMySQL-1.0.2-py3-none-any.whl (43kB)
Collecting openpyxl~=3.0.0 (from awswrangler==2.4.0->-r /usr/local/airflow/requirements/requirements.txt (line 1))
Downloading https://files.pythonhosted.org/packages/d4/c5/1a5f82b3020bfb27f21b302f96c8ae6a34475070015d1b1e0b197a97e2af/openpyxl-3.0.6-py2.py3-none-any.whl (242kB)
Collecting pyarrow<3.1.0,>=2.0.0 (from awswrangler==2.4.0->-r /usr/local/airflow/requirements/requirements.txt (line 1))
Downloading https://files.pythonhosted.org/packages/62/d3/a482d8a4039bf931ed6388308f0cc0541d0cab46f0bbff7c897a74f1c576/pyarrow-3.0.0.tar.gz (682kB)
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-build-d04tweyh/pyarrow/setup.py", line 37, in <module>
from Cython.Distutils import build_ext as _build_ext
ModuleNotFoundError: No module named 'Cython'
 
----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-d04tweyh/pyarrow/

```
I have tested with awswrangler==2.3.0 (it comes with pyarrow 2.0.0), and it works.
But I'm looking to install awswrangler==2.4.0 on MWAA.

Python version = 3.7
AWSWRANGLER version = 2.4.0

Steps:
Contents of requirements.txt file to be uploaded in MWAA.
`awswrangler==2.4.0`
1. Upload this file to S3.
2. Refer this file as the requirements.txt while creating/updating MWAA environment.
3. Proceed to creating/updating the environment.

**Comment by jaidisido** [comment]
Similar to [EMR and Glue jobs](https://aws-data-wrangler.readthedocs.io/en/2.4.0-docs/install.html?highlight=pyarrow%203.0), PyArrow 3.0 is not currently supported on MWAA, which is why a previous installation of PyArrow 2 is required.

For these services you can run: `pip install pyarrow==2 awswrangler`

More details in this [issue](https://github.com/awslabs/aws-data-wrangler/issues/546).
