### ISSUE TITLE
Cannot import awswrangler : AttributeError: module 'multiprocessing' has no attribute 'connection'

### ISSUE THREAD

**Issue by adtsai-duetto** [awslabs/aws-data-wrangler#628]
Cannot import awswrangler

import awswrangler as wr
Traceback (most recent call last):

  File "<ipython-input-1-21c45332ee4c>", line 1, in <module>
    import awswrangler as wr

  File "/opt/anaconda3/lib/python3.8/site-packages/awswrangler/__init__.py", line 17, in <module>
    from awswrangler.pandas import Pandas  # noqa

  File "/opt/anaconda3/lib/python3.8/site-packages/awswrangler/pandas.py", line 45, in <module>
    class Pandas:

  File "/opt/anaconda3/lib/python3.8/site-packages/awswrangler/pandas.py", line 273, in Pandas
    def _read_csv_once_remote(send_pipe: mp.connection.Connection, session_primitives: "SessionPrimitives",

AttributeError: module 'multiprocessing' has no attribute 'connection'

Latest Anaconda Python release 3.8 updated.

**Comment by maxispeicher** [comment]
A install from conda-forge in the default environment installs a very old version of `awswrangler`. So probably installing in a newly created environment should fix the issue. You can have a look at https://github.com/awslabs/aws-data-wrangler/issues/577 for some more information.
