### ISSUE TITLE
Nested Json File gives pyarrow.lib.ArrowInvalid

### ISSUE THREAD

**Issue by adarsh-chauhan** [awslabs/aws-data-wrangler#647]
We are receiving nested json response from a third party provider.

json Schema 
```
root
 |-- items: array 
 |    |-- element: struct
 |    |    |-- show_title_id: integer
 |    |    |-- duration: double
 |    |    |--subelement: struct
 |    |    |-- ts: str  <----the value at the end of stack trace points to this
```

We try to convert the json data to parquet only for few files we receive the following error:

```

2021-04-11T22:15:42.515+05:30	Traceback (most recent call last):

2021-04-11T22:15:42.515+05:30	s3_additional_kwargs={"ACL": "bucket-owner-full-control"},

2021-04-11T22:15:42.515+05:30	File "/opt/amazon/lib/python3.7/site-packages/awswrangler/_config.py", line 417, in wrapper

2021-04-11T22:15:42.515+05:30	return function(**args)

2021-04-11T22:15:42.515+05:30	File "/opt/amazon/lib/python3.7/site-packages/awswrangler/s3/_write_parquet.py", line 530, in to_parquet

2021-04-11T22:15:42.515+05:30	df=df, index=index, ignore_cols=partition_cols, dtype=dtype

2021-04-11T22:15:42.515+05:30	File "/opt/amazon/lib/python3.7/site-packages/awswrangler/_data_types.py", line 571, in pyarrow_schema_from_pandas

2021-04-11T22:15:42.515+05:30	df=df, index=index, ignore_cols=ignore_plus

2021-04-11T22:15:42.515+05:30	File "/opt/amazon/lib/python3.7/site-packages/awswrangler/_data_types.py", line 442, in pyarrow_types_from_pandas

2021-04-11T22:15:42.515+05:30	cols_dtypes[col] = process_not_inferred_dtype(ex)

2021-04-11T22:15:42.515+05:30	File "/opt/amazon/lib/python3.7/site-packages/awswrangler/_data_types.py", line 487, in process_not_inferred_dtype

2021-04-11T22:15:42.515+05:30	raise ex

2021-04-11T22:15:42.515+05:30	File "/opt/amazon/lib/python3.7/site-packages/awswrangler/_data_types.py", line 440, in pyarrow_types_from_pandas

2021-04-11T22:15:42.515+05:30	schema: pa.Schema = pa.Schema.from_pandas(df=df[[col]], preserve_index=False)

2021-04-11T22:15:42.515+05:30	File "pyarrow/types.pxi", line 1344, in pyarrow.lib.Schema.from_pandas

2021-04-11T22:15:42.515+05:30	File "/opt/amazon/lib/python3.7/site-packages/pyarrow/pandas_compat.py", line 529, in dataframe_to_types

2021-04-11T22:15:42.515+05:30	type_ = pa.array(c, from_pandas=True).type

2021-04-11T22:15:42.515+05:30	File "pyarrow/array.pxi", line 292, in pyarrow.lib.array

2021-04-11T22:15:42.515+05:30	File "pyarrow/array.pxi", line 83, in pyarrow.lib._ndarray_to_array

2021-04-11T22:15:42.515+05:30	File "pyarrow/error.pxi", line 84, in pyarrow.lib.check_status

2021-04-11T22:15:42.515+05:30	pyarrow.lib.ArrowInvalid: Could not convert 1615227651.079300 with type str: tried to convert to int
```

I am unable to understand why we are getting this error

```
  Python-awswrangler-2.x = 2.x.2302.0
  Apache-arrow-cpp-2.x = 2.x.1323.0
  Python-pyarrow-2.x = 2.x.1410.0
```

**Comment by maxispeicher** [comment]
Normally this error occurs when you have different data types in your the column of your original df. Easy example for reproducing:
```python
import time

import pandas as pd
import pyarrow as  pa

df = pd.DataFrame({"c0": [int(time.time()), str(time.time())]})
print(df)
#                    c0
# 0          1618227344
# 1  1618227344.8929965

schema = pa.Schema.from_pandas(df=df[["c0"]])
```
results in
```
pyarrow.lib.ArrowInvalid: Could not convert 1618227344.8929965 with type str: tried to convert to int
```

In order to fix it you need to change the column dtype beforehand like:
```python
import time

import pandas as pd
import pyarrow as  pa

df = pd.DataFrame({"c0": [int(time.time()), str(time.time())]})
df["c0"] = df["c0"].astype(float)

schema = pa.Schema.from_pandas(df=df[["c0"]])
```
which then generates the desired schema.

**Comment by adarsh-chauhan** [comment]
@maxispeicher Thanks for the quick response and the elaborated example.
let me cross check the data we are receiving.

**Comment by adarsh-chauhan** [comment]
@maxispeicher I can confirm that the provider has discrepancy for few fields.
Since now its not in our control it might take months to get this fixed from provider end.

So my question is is there a way where i can say or configure that where ever `ts` is encountered convert it to string in a **nested** json

**Comment by maxispeicher** [comment]
Just to make sure: How exactly are you receiving the data respectively parsing the data into a DataFrame. Do you have a JSON file which you are parsing? If so and `ts` can be nested at every level, probably it would be to load the json and just iterate over the structure and let all `ts` values be casted to the appropiate datatype with the help of a recursive function, before passing it to pandas.
But I'm sure there are other ways aswell.

Maybe it would also help two add some information, how the `df` handed over to `awswrangler` really looks like. (e.g. columns, dtypes and if possible head)

**Comment by adarsh-chauhan** [comment]
@maxispeicher yes a json file is being fed to pandas

```
    dataframe = pandas.json_normalize(
        conversation_file.json_data.get('x')
    )
```

```
    upload_response = awswrangler.s3.to_parquet(
        df=data_frame,
        path=s3_path,
        dataset=True,
        s3_additional_kwargs={"ACL": "bucket-owner-full-control"},
    )
```

**Comment by maxispeicher** [comment]
If you are using `json_normalize`, `ts` should always be in the column name. Therefore you could probably use something like:
```python
for col in df.columns:
    if "ts" in col:
        df[col] = df[col].astype(float)
```

**Comment by adarsh-chauhan** [comment]
@maxispeicher 
we found the `ts` throwing error was deeply nested and was present at couple of places with at times as `int` and at times as `string`

```
def sanitize_ts(dataframe):
    for attachment_type in ['attachments', 'root.attachment','previous.attachments']:
        if attachment_type in enhanced_dataframe.columns:
            for attachments in enhanced_dataframe[enhanced_dataframe[attachment_type].notnull()][attachment_type]:
                for attachment in attachments:
                    ts = attachment.get('ts')
                    if ts and '.' not in str(ts):
                        attachment['ts'] = str(ts) + '.000000'
```

But really appreciate your help on this. your example really helped me to find the root cause
