### ISSUE TITLE
Repeated calls to wr.redshift.to_sql() fail

### ISSUE THREAD

**Issue by kukushking** [awslabs/aws-data-wrangler#680]
**Describe the bug**
See the code below.

**To Reproduce**
```
import awswrangler as wr
import pandas as pd
df = pd.DataFrame({"c0": [1, 2, 3], "c1": ["foo", "boo", "bar"]})
con = wr.redshift.connect("aws-data-wrangler-redshift")
wr.redshift.to_sql(df, con, "hello", "public", "overwrite", True)
wr.redshift.to_sql(df, con, "hello", "public", "overwrite", True)
wr.redshift.to_sql(df, con, "hello", "public", "overwrite", True)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Volumes/workplace/github.com/aws-data-wrangler/pyenv-shim-venv/lib/python3.7/site-packages/awswrangler/_config.py", line 417, in wrapper
    return function(**args)
  File "/Volumes/workplace/github.com/aws-data-wrangler/pyenv-shim-venv/lib/python3.7/site-packages/awswrangler/redshift.py", line 747, in to_sql
    df.reset_index(level=df.index.names, inplace=True)
  File "/Volumes/workplace/github.com/aws-data-wrangler/pyenv-shim-venv/lib/python3.7/site-packages/pandas/core/frame.py", line 5016, in reset_index
    new_obj.insert(0, name, level_values)
  File "/Volumes/workplace/github.com/aws-data-wrangler/pyenv-shim-venv/lib/python3.7/site-packages/pandas/core/frame.py", line 3763, in insert
    self._mgr.insert(loc, column, value, allow_duplicates=allow_duplicates)
  File "/Volumes/workplace/github.com/aws-data-wrangler/pyenv-shim-venv/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 1191, in insert
    raise ValueError(f"cannot insert {item}, already exists")
ValueError: cannot insert level_0, already exists

```

**Comment by kukushking** [comment]
```
reset_index(drop=True)
```
Should fix it -- will send PR today.

**Comment by kukushking** [comment]
Bizarre - I can't reproduce the issue anymore. Closing.
