### ISSUE TITLE
Unexpected Behavior in read_csv() with max_result_size

### ISSUE THREAD

**Issue by BellyTheMagnificent** [awslabs/aws-data-wrangler#71]
I'm using the read_csv() with max_result_size of 128mb to process a 135mb csv file. When attempt to write parquet, it return the following error:

`Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/root/environment/demo/lib64/python3.6/dist-packages/awswrangler/pandas.py", line 815, in _data_to_s3_dataset_writer_remote
    isolated_dataframe=True))
  File "/home/root/environment/demo/lib64/python3.6/dist-packages/awswrangler/pandas.py", line 758, in _data_to_s3_dataset_writer
    isolated_dataframe=isolated_dataframe)
  File "/home/root/environment/demo/lib64/python3.6/dist-packages/awswrangler/pandas.py", line 856, in _data_to_s3_object_writer
    isolated_dataframe=isolated_dataframe)
  File "/home/root/environment/demo/lib64/python3.6/dist-packages/awswrangler/pandas.py", line 902, in write_parquet_dataframe
    table = pa.Table.from_pandas(df=dataframe, preserve_index=preserve_index, safe=False)
  File "pyarrow/table.pxi", line 1174, in pyarrow.lib.Table.from_pandas
  File "/home/root/environment/demo/lib64/python3.6/dist-packages/pyarrow/pandas_compat.py", line 501, in dataframe_to_arrays
    convert_fields))
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/root/environment/demo/lib64/python3.6/dist-packages/pyarrow/pandas_compat.py", line 487, in convert_column
    raise e
  File "/home/root/environment/demo/lib64/python3.6/dist-packages/pyarrow/pandas_compat.py", line 481, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 191, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 78, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 95, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: ("Expected a bytes object, got a 'Timestamp' object", 'Conversion failed for column xxxxx with type object')`

When process the same file using read_csv() without max_result_size, it work fine.

Code Snippet:

> df_iter = session.pandas.read_csv(csv, sep='|', header=0, dtype=file_meta,  parse_dates=dates_cols, max_result_size=128*1024*1024)

> for df in df_iter:
>       df_data=df_data.append(df)  

>session.pandas.to_parquet(dataframe=df_data,database=db_name,table=tbl_name,preserve_index=False,mode='overwrite', path=path)

**Comment by igorborgest** [comment]
This looks like some issue with data types related to the CSV inference.
I suppose that your dataset is confidential, so I will need your help to try to troubleshoot it.

Can you print some infos inside your loop?

```py3
for df in df_iter:
    print(len(df.index))
    print(len(df.columns))
    print(df.dtypes)
    df_data=df_data.append(df)
```

And compare some aspects between the output of running with max_result_size and without:

- The total number of rows and columns between all the dataframes make sense?
- The data types between all the dataframes are igual?

Thanks!

**Comment by BellyTheMagnificent** [comment]
Hi,

- The total number of rows and columns between all the dataframes make sense?
_total number of rows and columns intact_ 

- The data types between all the dataframes are igual?
No. One of the date field is classify as **datetime64[ns]** data type on first iteration, then become **object** in second iteration
For the dataframe create from read_csv() without max_size_result, the data type is classify as **object**.

**Comment by igorborgest** [comment]
This problem is intrinsic to read CSV files. Unfortunately CSV doesn't have built-in schema nor hard data types.

After all, every value on a CSV is a string. Pandas or any other parser can try to infer the data type looking for a pattern on theses strings, but it will always be a guess.

So in your case Pandas is inferring two different data types for the two parts of your dataset, probably you should have some weird value in the last part of your file that does not fit so good as a timestamp.

The solutions that I see now are:
* Read the entire dataframe at once to guarantee data type consistency
* Cast the values to the know data type
* Rely on an external schema like Athena does.

I will close this issue because there is no way to help from the library side. But let us know with you have some question or suggestion.

**Comment by BellyTheMagnificent** [comment]
We tr
Noted. Will try to cast the data types explicitly.

**Comment by igorborgest** [comment]
In this case you should try to cast to the most general type between both -> object (string)
