### ISSUE TITLE
Not support Array_column

### ISSUE THREAD

**Issue by kfunamizu** [awslabs/aws-data-wrangler#72]
An error occurs when execute a query against a table containing array<string>_column

>>> session.pandas.read_sql_athena(
...     sql="select * from xxxx limit 100",
...     database="xxxx"
... )

Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/usr/local/lib/python3.6/site-packages/awswrangler/pandas.py", line 477, in read_sql_athena
    max_result_size=max_result_size)
  File "/usr/local/lib/python3.6/site-packages/awswrangler/pandas.py", line 136, in read_csv
    converters=converters)
  File "/usr/local/lib/python3.6/site-packages/awswrangler/pandas.py", line 417, in _read_csv_once
    converters=converters,
  File "/usr/local/lib64/python3.6/site-packages/pandas/io/parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib64/python3.6/site-packages/pandas/io/parsers.py", line 463, in _read
    data = parser.read(nrows)
  File "/usr/local/lib64/python3.6/site-packages/pandas/io/parsers.py", line 1154, in read
    ret = self._engine.read(nrows)
  File "/usr/local/lib64/python3.6/site-packages/pandas/io/parsers.py", line 2059, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 881, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 896, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 973, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 1083, in pandas._libs.parsers.TextReader._convert_column_data
  File "pandas/_libs/parsers.pyx", line 2231, in pandas._libs.parsers._apply_converter
  File "/usr/lib64/python3.6/ast.py", line 48, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/lib64/python3.6/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    [xxxxx]

**Comment by igorborgest** [comment]
Hi @Koshi-Funamizu, thank you for open this issue.

Which is the full data type of your array column? (e.g. array<integer>)

**Comment by Koshi-Funamizu** [comment]
`array<string>`

```
CREATE EXTERNAL TABLE `sample`(
  `yyy` timestamp, 
  `xxx` string, 
  `zzz` array<string>, 
  `yyyxxx` array<string>, 
  `xxxzzz` string)
PARTITIONED BY ( 
  `year` string, 
  `month` string, 
  `day` string)
```

**Comment by igorborgest** [comment]
Fixed. Will be released tomorrow in the new version!
