### ISSUE TITLE
Athena unsupported type timestamp without time zone

### ISSUE THREAD

**Issue by Gonalb** [awslabs/aws-data-wrangler#800]
I'm tryng to insert registers in redshift using the wrangler library and return me the folowing error:

```
[INFO]	2021-07-07T13:43:26.370Z	64072650-f26d-46d8-a852-5eaa5c5b4bfc	Errors: b'OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k\n/tmp/tb_analytics_processor.py:19: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module\'s documentation for alternative uses\n  import imp\nINFO:__main__:Loading Job module.\nINFO:__main__:Running Script odl_transformation_lambda_processor.\nINFO:__main__:entro al run\nINFO:__main__:execute_spark_transform: False\nINFO:__main__:arn:aws:xxxxxxxxx:role/iam_r_xxxx_arg_datalake_dev_s3datalake_redshift\nINFO:__main__:key_sql\nINFO:__main__:tr_mx_xxxx_reportedeservicio_analytics.sql\nINFO:__main__:bucket_sql\nINFO:__main__:xxxx-arg-datalake-transform-dev\nINFO:__main__:partition\nINFO:__main__:dt=2021-06-23\nINFO:__main__:2021-06-23\nINFO:__main__:target_partition_dt_field\nINFO:__main__:dt\nINFO:__main__:True\nINFO:__main__:entro a custom transform\nINFO:customtransform:Entering Lambda Custom Transform\nINFO:customtransform:Getting props data\nINFO:customtransform:Reading file : s3://xxxx-arg-datalake-stage-dev/mx/xxxx/reportedeserviciobancar/dt=2021-06-23/77102349b95d41b89da07ac32f76bb19.snappy.parquet\nINFO:customtransform:Creating date column\nINFO:customtransform:Changing datatypes\nINFO:customtransform:Custom transform finished\nINFO:__main__:imprimiendo el resultado de resultdf \nINFO:__main__:                                             guide_number  ...          dt\n0       N\xc3\xbamero de Gu\xc3\xada ,Fecha de Confirmaci\xc3\xb3n,C\xc3\xb3digo d...  ...  2021-06-23\n1       601588799961A602778243,03/09/2020 15:54,274975...  ...  2021-06-23\n2       301588799961A602778254,07/09/2020 00:00,186356...  ...  2021-06-23\n3       501588799961A602778253,03/09/2020 15:43,220662...  ...  2021-06-23\n4       901588799961A602778256,03/09/2020 11:20,370029...  ...  2021-06-23\n...                                                   ...  ...         ...\n130641  901588799961A604158995,,3769516424,PENDIENTE,2...  ...  2021-06-23\n130642  901588799961A604159003,,1868694302,PENDIENTE,2...  ...  2021-06-23\n130643  901588799961A604159008,,4172339862,PENDIENTE,2...  ...  2021-06-23\n130644  901588799961A604159022,2021-06-19 11:21:00,071...  ...  2021-06-23\n130645  901588799961A604159027,2021-06-19 13:07:00,151...  ...  2021-06-23\n\n[130646 rows x 16 columns]\nINFO:__main__:resulquery()\nINFO:__main__:                                             guide_number  ...          dt\n0       N\xc3\xbamero de Gu\xc3\xada ,Fecha de Confirmaci\xc3\xb3n,C\xc3\xb3digo d...  ...  2021-06-23\n1       601588799961A602778243,03/09/2020 15:54,274975...  ...  2021-06-23\n2       301588799961A602778254,07/09/2020 00:00,186356...  ...  2021-06-23\n3       501588799961A602778253,03/09/2020 15:43,220662...  ...  2021-06-23\n4       901588799961A602778256,03/09/2020 11:20,370029...  ...  2021-06-23\n...                                                   ...  ...         ...\n130641  901588799961A604158995,,3769516424,PENDIENTE,2...  ...  2021-06-23\n130642  901588799961A604159003,,1868694302,PENDIENTE,2...  ...  2021-06-23\n130643  901588799961A604159008,,4172339862,PENDIENTE,2...  ...  2021-06-23\n130644  901588799961A604159022,2021-06-19 11:21:00,071...  ...  2021-06-23\n130645  901588799961A604159027,2021-06-19 13:07:00,151...  ...  2021-06-23\n\n[130646 rows x 16 columns]\nINFO:__main__:target partition is not none\nINFO:__main__:pathsssss\nINFO:__main__:[\'s3://xxxxxxx-datalake-analytics-dev/mx/tb_mx_xxxx_reporte_de_servicio/dt=2021-06-23/61f4fe8e0b2e44f29f6ba41e4509d0dc.snappy.parquet\']\nINFO:__main__:s3://xxxxx-datalake-analytics-dev/mx/tb_xxxxxx_reporte_de_servicio/dt=2021-06-23/61f4fe8e0b2e44f29f6ba41e4509d0dc.snappy.parquet\nINFO:__main__:Wrote the analytics directory output using business date partition\nINFO:__main__:Checking target table definition information in PG_TABLE_DEF for Redshift\nINFO:__main__:Redshift Write :\n        table : tb_mx_xxxx_reporte_de_servicio\n        mode : Append\n        iam_role : arn:aws:xxxxxxxxx:role/iam_r_xxxxx_datalake_dev_s3datalake_redshift\n        primary_keys : False\n        path : s3://xxxx-arg-datalake-redshift-dev/9179d751-cc75-4f81-bd54-b2996b6f1bcc/\n        \nERROR:__main__:Redshift Write Exception on table tb_mxxx_reporte_de_servicio: Unsupported Athena type: timestamp without time zone\nERROR:__main__:Traceback : Traceback (most recent call last):\n  File "/tmp/tb_analytics_processor.py", line 292, in writeToRedshift\n    dtype=dict_dtypes\n  File "/opt/python/awswrangler/redshift.py", line 1246, in copy\n    max_rows_by_file=max_rows_by_file,\n  File "/opt/python/awswrangler/_config.py", line 361, in wrapper\n    return function(**args)\n  File "/opt/python/awswrangler/s3/_write_parquet.py", line 486, in to_parquet\n    df = _apply_dtype(df=df, dtype=dtype, catalog_table_input=catalog_table_input, mode=mode)\n  File "/opt/python/awswrangler/s3/_write.py", line 34, in _apply_dtype\n    df = _data_types.cast_pandas_with_athena_types(df=df, dtype=dtype)\n  File "/opt/python/awswrangler/_data_types.py", line 558, in cast_pandas_with_athena_types\n    desired_type: str = athena2pandas(dtype=athena_type)\n  File "/opt/python/awswrangler/_data_types.py", line 283, in athena2pandas\n    raise exceptions.UnsupportedType(f"Unsupported Athena type: {dtype}")\nawswrangler.exceptions.UnsupportedType: Unsupported Athena type: timestamp without time zone\n\n'
[INFO] 2021-07-07T13:43:26.370Z 64072650-f26d-46d8-a852-5eaa5c5b4bfc Errors: b'OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k\n/tmp/tb_analytics_processor.py:19: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module\'s documentation for alternative uses\n import imp\nINFO:__main__:Loading Job module.\nINFO:__main__:Running Script odl_transformation_lambda_processor.\nINFO:__main__:entro al run\nINFO:__main__:execute_spark_transform: False\nINFO:__main__:arn:aws:xxxxxxxxx:role/iam_r_xxxx_arg_datalake_dev_s3datalake_redshift\nINFO:__main__:key_sql\nINFO:__main__:tr_mx_xxxx_reportedeservicio_analytics.sql\nINFO:__main__:bucket_sql\nINFO:__main__:xxxx-arg-datalake-transform-dev\nINFO:__main__:partition\nINFO:__main__:dt=2021-06-23\nINFO:__main__:2021-06-23\nINFO:__main__:target_partition_dt_field\nINFO:__main__:dt\nINFO:__main__:True\nINFO:__main__:entro a custom transform\nINFO:customtransform:Entering Lambda Custom Transform\nINFO:customtransform:Getting props data\nINFO:customtransform:Reading file : s3://xxxx-arg-datalake-stage-dev/mx/xxxx/reportedeserviciobancar/dt=2021-06-23/77102349b95d41b89da07ac32f76bb19.snappy.parquet\nINFO:customtransform:Creating date column\nINFO:customtransform:Changing datatypes\nINFO:customtransform:Custom transform finished\nINFO:__main__:imprimiendo el resultado de resultdf \nINFO:__main__: guide_number ... dt\n0 N\xc3\xbamero de Gu\xc3\xada ,Fecha de Confirmaci\xc3\xb3n,C\xc3\xb3digo d... ... 2021-06-23\n1 601588799961A602778243,03/09/2020 15:54,274975... ... 2021-06-23\n2 301588799961A602778254,07/09/2020 00:00,186356... ... 2021-06-23\n3 501588799961A602778253,03/09/2020 15:43,220662... ... 2021-06-23\n4 901588799961A602778256,03/09/2020 11:20,370029... ... 2021-06-23\n... ... ... ...\n130641 901588799961A604158995,,3769516424,PENDIENTE,2... ... 2021-06-23\n130642 901588799961A604159003,,1868694302,PENDIENTE,2... ... 2021-06-23\n130643 901588799961A604159008,,4172339862,PENDIENTE,2... ... 2021-06-23\n130644 901588799961A604159022,2021-06-19 11:21:00,071... ... 2021-06-23\n130645 901588799961A604159027,2021-06-19 13:07:00,151... ... 2021-06-23\n\n[130646 rows x 16 columns]\nINFO:__main__:resulquery()\nINFO:__main__: guide_number ... dt\n0 N\xc3\xbamero de Gu\xc3\xada ,Fecha de Confirmaci\xc3\xb3n,C\xc3\xb3digo d... ... 2021-06-23\n1 601588799961A602778243,03/09/2020 15:54,274975... ... 2021-06-23\n2 301588799961A602778254,07/09/2020 00:00,186356... ... 2021-06-23\n3 501588799961A602778253,03/09/2020 15:43,220662... ... 2021-06-23\n4 901588799961A602778256,03/09/2020 11:20,370029... ... 2021-06-23\n... ... ... ...\n130641 901588799961A604158995,,3769516424,PENDIENTE,2... ... 2021-06-23\n130642 901588799961A604159003,,1868694302,PENDIENTE,2... ... 2021-06-23\n130643 901588799961A604159008,,4172339862,PENDIENTE,2... ... 2021-06-23\n130644 901588799961A604159022,2021-06-19 11:21:00,071... ... 2021-06-23\n130645 901588799961A604159027,2021-06-19 13:07:00,151... ... 2021-06-23\n\n[130646 rows x 16 columns]\nINFO:__main__:target partition is not none\nINFO:__main__:pathsssss\nINFO:__main__:[\'s3://xxxx-arg-datalake-analytics-dev/mx/tb_mx_xxxx_reporte_de_servicio/dt=2021-06-23/61f4fe8e0b2e44f29f6ba41e4509d0dc.snappy.parquet\']\nINFO:__main__:s3://xxxx-arg-datalake-analytics-dev/mx/tb_mx_xxxx_reporte_de_servicio/dt=2021-06-23/61f4fe8e0b2e44f29f6ba41e4509d0dc.snappy.parquet\nINFO:__main__:Wrote the analytics directory output using business date partition\nINFO:__main__:Checking target table definition information in PG_TABLE_DEF for Redshift\nINFO:__main__:Redshift Write :\n table : tb_mx_xxxx_reporte_de_servicio\n mode : Append\n iam_role : arn:aws:xxxxxxxxx:role/iam_r_xxxx_arg_datalake_dev_s3datalake_redshift\n primary_keys : False\n path : s3://xxxx-arg-datalake-redshift-dev/9179d751-cc75-4f81-bd54-b2996b6f1bcc/\n \nERROR:__main__:Redshift Write Exception on table tb_mx_xxxx_reporte_de_servicio: Unsupported Athena type: timestamp without time zone\nERROR:__main__:Traceback : Traceback (most recent call last):\n File "/tmp/tb_analytics_processor.py", line 292, in writeToRedshift\n dtype=dict_dtypes\n File "/opt/python/awswrangler/redshift.py", line 1246, in copy\n max_rows_by_file=max_rows_by_file,\n File "/opt/python/awswrangler/_config.py", line 361, in wrapper\n return function(**args)\n File "/opt/python/awswrangler/s3/_write_parquet.py", line 486, in to_parquet\n df = _apply_dtype(df=df, dtype=dtype, catalog_table_input=catalog_table_input, mode=mode)\n File "/opt/python/awswrangler/s3/_write.py", line 34, in _apply_dtype\n df = _data_types.cast_pandas_with_athena_types(df=df, dtype=dtype)\n File "/opt/python/awswrangler/_data_types.py", line 558, in cast_pandas_with_athena_types\n desired_type: str = athena2pandas(dtype=athena_type)\n File "/opt/python/awswrangler/_data_types.py", line 283, in athena2pandas\n raise exceptions.UnsupportedType(f"Unsupported Athena type: {dtype}")\nawswrangler.exceptions.UnsupportedType: Unsupported Athena type: timestamp without time zone\n\n'
```

**Comment by jaidisido** [comment]
From the error it seems that a timestamp column in the input dataframe can be cast to a valid Athena type. Could you please share a snippet of the dataframe and the data it holds so we can reproduce the issue on our end? Thanks
