### ISSUE TITLE
STS Timeout using athena.read_sql

### ISSUE THREAD

**Issue by kev-dfs** [awslabs/aws-data-wrangler#826]
*P.S. Don't attach files. Please, prefer add code snippets directly in the message body.*

Hi, 

I created a Glue Job with a sample implementation, I'm using athena.read_sql to read a table from my glue catalog. 
But I have an error...

In the Logs of Cloudwatch say this: 

Traceback (most recent call last):
  File "/home/spark/.local/lib/python3.7/site-packages/botocore/httpsession.py", line 263, in send
    chunked=self._chunked(request.headers),
  File "/home/spark/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/spark/.local/lib/python3.7/site-packages/urllib3/util/retry.py", line 376, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/spark/.local/lib/python3.7/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/home/spark/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/spark/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/home/spark/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/home/spark/.local/lib/python3.7/site-packages/urllib3/connection.py", line 300, in connect
    conn = self._new_conn()
  File "/home/spark/.local/lib/python3.7/site-packages/urllib3/connection.py", line 164, in _new_conn
    % (self.host, self.timeout),
urllib3.exceptions.ConnectTimeoutError: (<botocore.awsrequest.AWSHTTPSConnection object at 0x7f733f8448d0>, 'Connection to sts.amazonaws.com timed out. (connect timeout=10)')

In the Glue Console say this:

ConnectTimeoutError: Connect timeout on endpoint URL: "https://sts.amazonaws.com/"

What could be the error? and, Why need access to sts this function?

Thanks.

**Comment by maxispeicher** [comment]
Are you calling `create_athena_bucket` in your job? This function does use `sts` for determining the account id.

Regarding the error itself, my guess would be that your Glue job has no public internet access. Therefore, you could use an internal STS endpoint and configure it via the [global configurations](https://github.com/awslabs/aws-data-wrangler/blob/main/tutorials/021%20-%20Global%20Configurations.ipynb).

**Comment by jaidisido** [comment]
As Max mentioned your issue is likely related to your Glue Job needing a [Glue Connection](https://docs.aws.amazon.com/glue/latest/dg/connection-using.html) as it does not seem able to reach other services at the moment. From the error trace, your issue does not seem Wrangler specific and should occur with other libraries/commands making AWS API calls from your [Glue job](https://stackoverflow.com/questions/67320737/aws-glue-job-fails-with-connection-timeout-error).

**Comment by kev-dfs** [comment]
Hi @maxispeicher ,

The functions that i'm using are: 

- wr.athena.read_sql
- wr.s3.read_csv
- wr.s3.read_excel
- wr.s3.to_excel

I'm not using `create_athena_bucket` (maybe some function use this on back?)

**Comment by maxispeicher** [comment]
Thank you for the insights @kev-dfs. However, I can not see where any of the functions would call `sts`. I think that there is something else in your script that performs the `sts` calls.

In the complete traceback it should actually be visible which call from your script eventually results in the exception.

**Comment by kev-dfs** [comment]
@maxispeicher @jaidisido Thanks for your help, I had a glue connection error.
Now, the error is not a timeout, is a library error when I execute the function `wr.athena.read_sql_query`.
The error in glue is: 
`TypeError: to_pandas() got an unexpected keyword argument 'safe' `

The error in cloudwatch is:

2021-07-21 17:28:52,841 ERROR [main] glue.ProcessLauncher (Logging.scala:logError(70)): Error from Python:Traceback (most recent call last):
  File "/tmp/file_job", line 33, in <module>
    df_sample = wr.athena.read_sql_query(query_sample, database= "database_sample")
  File "/tmp/awswrangler-2.9.0-py3-none-any.whl/awswrangler/_config.py", line 417, in wrapper
    return function(**args)
  File "/tmp/awswrangler-2.9.0-py3-none-any.whl/awswrangler/athena/_read.py", line 844, in read_sql_query
    boto3_session=session,
  File "/tmp/awswrangler-2.9.0-py3-none-any.whl/awswrangler/athena/_read.py", line 558, in _resolve_query_without_cache
    boto3_session=boto3_session,
  File "/tmp/awswrangler-2.9.0-py3-none-any.whl/awswrangler/athena/_read.py", line 460, in _resolve_query_without_cache_ctas
    temp_table_fqn=fully_qualified_name,
  File "/tmp/awswrangler-2.9.0-py3-none-any.whl/awswrangler/athena/_read.py", line 251, in _fetch_parquet_result
    ignore_index=True,
  File "/tmp/awswrangler-2.9.0-py3-none-any.whl/awswrangler/s3/_read_parquet.py", line 721, in read_parquet
    read_func=_read_parquet, paths=paths, version_ids=versions, use_threads=use_threads, kwargs=args
  File "/tmp/awswrangler-2.9.0-py3-none-any.whl/awswrangler/s3/_read.py", line 145, in _read_dfs_from_multiple_paths
    return list(df for df in executor.map(partial_read_func, paths, versions))
  File "/tmp/awswrangler-2.9.0-py3-none-any.whl/awswrangler/s3/_read.py", line 145, in <genexpr>
    return list(df for df in executor.map(partial_read_func, paths, versions))
  File "/usr/lib64/python3.7/concurrent/futures/_base.py", line 598, in result_iterator
    yield fs.pop().result()
  File "/usr/lib64/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/usr/lib64/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib64/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/awswrangler-2.9.0-py3-none-any.whl/awswrangler/s3/_read_parquet.py", line 503, in _read_parquet
    path_root=path_root,
  File "/tmp/awswrangler-2.9.0-py3-none-any.whl/awswrangler/s3/_read_parquet.py", line 285, in _arrowtable2df
    types_mapper=_data_types.pyarrow2pandas_extension if map_types else None,
  File "pyarrow/array.pxi", line 482, in pyarrow.lib._PandasConvertible.to_pandas
TypeError: to_pandas() got an unexpected keyword argument 'safe'

More context:
The query is executed on athena table, and the file is in parquet on s3.

What could be the cause of the error?

**Comment by maxispeicher** [comment]
Can you check which version of `pyarrow` is installed? I assume it's `2.0.0` as it is Glue and there the `safe` kwarg of `to_pandas` should be available: https://github.com/apache/arrow/blob/apache-arrow-2.0.0/python/pyarrow/array.pxi#L701.

**Comment by kev-dfs** [comment]
@maxispeicher 
I'm using pyarrow 2.0.0... 
The Glue Job run this command: `pip3 install --upgrade --user pyarrow==2 awswrangler==2.9.0`

I execute the code on a Jupyter Notebook (into Sagemaker) with pyarrow4 (default on Sagemaker) and this error don't exist. 
Is a bug in the library? How I can resolve this?

**Comment by kev-dfs** [comment]
Now Work! I print the version of modules and the pyarrow version was 0.15~ pip install had not worked correctly

Thanks for all.
