### ISSUE TITLE
s3.to_parquet with concurrent_partitioning=True issue

### ISSUE THREAD

**Issue by luca-ferreri** [awslabs/aws-data-wrangler#866]
**Describe the bug**

the first run of the to_parquet command
```python
to_parquet(
    df=df,
    path=f's3://{s3_bucket_forecast_name}/forecast_balance_processed/',
    index=False,
    dataset=True,
    filename_prefix=f'forecast_generated_',
    partition_cols=['date','user_id'],
    concurrent_partitioning=True,
    database=<example_db>,
    table=<example_table>,
    mode='append'
)
```
has the following error
```
Traceback (most recent call last):
  File "~\Anaconda3\envs\custom_lib\lib\site-packages\pandas\core\indexes\base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1625, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1632, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~\Anaconda3\envs\custom_lib\lib\site-packages\awswrangler\_config.py", line 417, in wrapper
    return function(**args)
  File "~\Anaconda3\envs\custom_lib\lib\site-packages\awswrangler\s3\_write_parquet.py", line 548, in to_parquet
    paths, partitions_values = _to_dataset(
  File "~\Anaconda3\envs\custom_lib\lib\site-packages\awswrangler\s3\_write_dataset.py", line 162, in _to_dataset
    paths, partitions_values = _to_partitions(
  File "~\Anaconda3\envs\custom_lib\lib\site-packages\awswrangler\s3\_write_dataset.py", line 68, in _to_partitions
    paths: List[str] = proxy.close()  # blocking
  File "~\Anaconda3\envs\custom_lib\lib\site-packages\awswrangler\s3\_write_concurrent.py", line 54, in close
    self._results += future.result()
  File "~\Anaconda3\envs\custom_lib\lib\concurrent\futures\_base.py", line 437, in result
    return self.__get_result()
  File "~\Anaconda3\envs\custom_lib\lib\concurrent\futures\_base.py", line 389, in __get_result
    raise self._exception
  File "~\Anaconda3\envs\custom_lib\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "~\Anaconda3\envs\custom_lib\lib\site-packages\awswrangler\s3\_write_concurrent.py", line 33, in _caller
    return func(**func_kwargs)
  File "~\Anaconda3\envs\custom_lib\lib\site-packages\awswrangler\s3\_write_parquet.py", line 146, in _to_parquet
    table: pa.Table = pyarrow.Table.from_pandas(df=df, schema=schema, nthreads=cpus, preserve_index=index, safe=True)
  File "pyarrow\table.pxi", line 1553, in pyarrow.lib.Table.from_pandas
  File "~\Anaconda3\envs\custom_lib\lib\site-packages\pyarrow\pandas_compat.py", line 607, in dataframe_to_arrays
    arrays[i] = maybe_fut.result()
  File "~\Anaconda3\envs\custom_lib\lib\concurrent\futures\_base.py", line 437, in result
    return self.__get_result()
  File "~\Anaconda3\envs\custom_lib\lib\concurrent\futures\_base.py", line 389, in __get_result
    raise self._exception
  File "~\Anaconda3\envs\custom_lib\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "~\Anaconda3\envs\custom_lib\lib\site-packages\pyarrow\pandas_compat.py", line 575, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow\array.pxi", line 306, in pyarrow.lib.array
  File "pyarrow\array.pxi", line 39, in pyarrow.lib._sequence_to_array
  File "pyarrow\error.pxi", line 141, in pyarrow.lib.pyarrow_internal_check_status
  File "~\Anaconda3\envs\custom_lib\lib\site-packages\pandas\core\series.py", line 853, in __getitem__
    return self._get_value(key)
  File "~\Anaconda3\envs\custom_lib\lib\site-packages\pandas\core\series.py", line 961, in _get_value
    loc = self.index.get_loc(label)
  File "~\Anaconda3\envs\custom_lib\lib\site-packages\pandas\core\indexes\base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 0
```
no problems if we set the `concurrent_partitioning=False` or from the second run of the very same command.

**Environment**

we are using awswrangler==2.10.0 and python==3.8

**To Reproduce**

1. create a Glue partitioned table called <example_table> and having parquet as data format.
2. run the following minimal python script:
```python
from datetime import datetime
from awswrangler.s3 import to_parquet
from pandas import read_json
s3_bucket_forecast_name = <bucket_name>

df = read_json('{"user_id":{"0":3050,"1":3050,"2":3050,"3":3050,"4":3050},"date":{"0":902707200000,"1":902793600000,"2":902880000000,"3":902966400000,"4":903052800000},"p10":{"0":56382.7541732031,"1":36138.2557973342,"2":44653.3919849297,"3":44118.3362647918,"4":45940.0631903547},"p50":{"0":79033.6523110692,"1":65850.661638426,"2":79387.5563623706,"3":80947.9655845604,"4":84234.2387350616},"p90":{"0":101684.5504489353,"1":95563.0674795178,"2":114121.7207398115,"3":117777.594904329,"4":122528.4142797684}}')
df['forecast_timestamp'] = datetime.now()

to_parquet(
    df=df,
    path=f's3://{s3_bucket_forecast_name}/forecast_balance_processed/',
    index=False,
    dataset=True,
    filename_prefix=f'forecast_generated_',
    partition_cols=['date','user_id'],
    concurrent_partitioning=True,
    database=<example_db>,
    table=<example_table>,
    mode='append'
)
```

**Comment by jaidisido** [comment]
Thanks for raising this @luca-ferreri, your issue is related to this [one](https://github.com/awslabs/aws-data-wrangler/issues/675). In short, it's a bug with one of our underlying dependencies: pyarrow (see [here](https://issues.apache.org/jira/browse/ARROW-12732) for more details). We have asked for a fix but still awaiting a [response](https://github.com/pandas-dev/pandas/issues/41432) (feel free to +1).

The current workaround is to add a cheap import of pyarrow before running your code:
```
from datetime import datetime
from awswrangler.s3 import to_parquet
from pandas import read_json, period_range, DataFrame
from pyarrow import table

table(DataFrame({'a': period_range("2012", freq="Y", periods=3)}))

s3_bucket_forecast_name = "my_bucket"
database = "my_db"
table = "my_tbl"

df = read_json('{"user_id":{"0":3050,"1":3050,"2":3050,"3":3050,"4":3050},"date":{"0":902707200000,"1":902793600000,"2":902880000000,"3":902966400000,"4":903052800000},"p10":{"0":56382.7541732031,"1":36138.2557973342,"2":44653.3919849297,"3":44118.3362647918,"4":45940.0631903547},"p50":{"0":79033.6523110692,"1":65850.661638426,"2":79387.5563623706,"3":80947.9655845604,"4":84234.2387350616},"p90":{"0":101684.5504489353,"1":95563.0674795178,"2":114121.7207398115,"3":117777.594904329,"4":122528.4142797684}}')
df['forecast_timestamp'] = datetime.now()

to_parquet(
    df=df,
    path=f's3://{s3_bucket_forecast_name}/forecast_balance_processed/',
    index=False,
    dataset=True,
    filename_prefix='forecast_generated_',
    partition_cols=['date', 'user_id'],
    concurrent_partitioning=True,
    database=database,
    table=table,
    mode='append',
)
```

Specifically this line:
```
table(DataFrame({'a': period_range("2012", freq="Y", periods=3)}))
```
will force an import of data types in the PyArrow library and the rest should work normally.

**Comment by luca-ferreri** [comment]
thank you @jaidisido, the workaround works in my case.
